name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # pour pouvoir publier une release GitHub
  issues: write # pour pouvoir commenter sur les issues
  pull-requests: write # pour pouvoir commenter sur les pull requests
  id-token: write # pour permettre l'utilisation de OIDC pour npm provenance

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: pnpm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
