name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Working Directory
        run: cd '/home/gwilym/Documents/mds/M2/dev mobile/pictionairy'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Semantic-release
        run: npx semantic-release
