name: Renovate

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes (for testing); you should adjust this for production
  push:
    branches:
      - main

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_AUTODISCOVER: "false" # Set to false since you're targeting a specific repo
        run: renovate Gwilymm/pictionairy
